Feature/error flow
psit4-lamas/PSIT4-LaMaS pull request #136
Opened 2019-05-06 21:33 UTC by tduong992

This PR solves:
- #131 Clearly define Error Flow
- replace user role with user username

2019-05-06 22:08 UTC, tduong992 commented
English:
![Screenshot 2019-05-06 20 58 07](https://user-images.githubusercontent.com/12140153/57258169-f1a57c80-705b-11e9-8c4d-3b5543767cc9.png)

German:
![Screenshot 2019-05-06 20 57 57](https://user-images.githubusercontent.com/12140153/57258185-fb2ee480-705b-11e9-932b-79a2fb7d082e.png)

2019-05-07 12:53 UTC, kernda02 commented
The error message "User not found" is also displayed with a correct user but wrong password. 
Should we rename "User not found" to "invalid credentials"?

2019-05-07 12:55 UTC, kernda02 commented on public/locales/de/translation.json
> +        "errorHeader": "Benutzer nicht gefunden",
change to "Ungültige Kombination Benuzter/Passwort"

2019-05-07 12:55 UTC, kernda02 commented on public/locales/en/translation.json
> +        "errorHeader": "User not found",
change to "invalid credentials"

2019-05-07 12:56 UTC, kernda02 requested changes
change "user not found" to "invalid credentials"

2019-05-10 20:03 UTC, wumacH commented
there are many messages defined we could retrieve from firebase in case of a unsuccessfull login (https://github.com/firebase/firebaseui-web/blob/master/soy/strings.soy), so i just changed the title of the message to a more general version (as you suggested)

2019-05-10 20:12 UTC, wumacH commented
ready to merge, thanks for your work :-)

2019-05-10 20:12 UTC, merged